#pragma once

//  Klassifikation von Feature-Typen, hauptsächlich für XPlanGML benötigt
enum OBJEKT_TYP  {  ANY_OBJEKT, BLEIT_PLAN, PLAN_BEREICH, XP_GEOMETRIE_OBJEKT, XP_PUNKT_OBJEKT, XP_LINIEN_OBJEKT, 
                    XP_FLAECHEN_OBJEKT, XP_PPO, XP_LPO, XP_FPO, XP_PTO, XP_LTO, RASTER_BASIS, RASTER_AENDERUNG, 
                    INSPIRE_PLU_OBJEKT, WEATHER_DATA, UNGUELTIG  };

// Klassifikation von GML-Attributen
enum ATTRIBUT_TYP  {  _ENUMERATION, _EXTERNAL_CODE_LIST, _EXTERNAL_CODE_LIST_GML3_3, _REFERENZ, _DATA_TYPE, _ANY_URI, _STRING, _DOUBLE, _INTEGER, _BOOLEAN, _DATE, _DATE_TIME,
					           _GEOMETRIE, _ANGLE, _LENGTH, _AREA, _VOLUME, _MEASURE, _POS_X, _POS_Y, _POS_XY, 	_DOMAIN_SET, _RANGE_SET, _RANGE_TYPE,
                     _CVGVP_DOMAIN_EXTENT, _CVGVP_ELEMENT, _ADDRESS, _MEASURE_LISTE, _QUANTITY_EXTENT, _TEXTE, _RASTERDARSTELLUNG,
                     TIME_POSITION, TIME_PERIOD, TIME_INTERVAL_LENGTH, TIME_SERIES,
                     REGULAR_TIME_SERIES, IRREGULAR_TIME_SERIES, REGULAR_TIME_SERIES_FILE, IRREGULAR_TIME_SERIES_FILE, ABSTRACT_TIME_SERIES,
                     _GENER_STRING, _GENER_DOUBLE, _GENER_INTEGER, _GENER_DATE, _GENER_URL, _GENER_MEASURE, _DIRECT_POSITION,
                     _GENER_LIST, _APPEARANCE, _SONST  };

//  Plan-Typ eines XPlanGML-Modells
enum XPLAN_TYP  { XPLAN, BPLAN, FPLAN, RPLAN, LPLAN, SOPLAN, KEIN_XPLAN  };

// Typ eines GML-Applikationsschemas
enum GML_SCHEMA_TYPE {  XPLANGML_2_0=2, XPLANGML_3_0=3, XPLANGML_4_0=4, XPLANGML_4_1=5, XPLANGML_5_0 = 6, XPLANGML_5_1 = 7, XPLANGML_5_2 = 8,
                        INSPIRE_LU_PLANNED=11, INSPIRE = 12,                         
                        NAS_5_1=20, NAS_5_1_1 = 21, NAS_6_0=22,
                        CITYGML_0_4_0=30, CITYGML_1_0=31, CITYGML_2_0=32, CITYGML_3_0=33,
                        BOREHOLEML_3_0 = 40,
                        GML_SCHEMA_DEFAULT = 60, GML_SCHEMA_UNKNOWN=99  };

//  Typ des GML-Basisschemas
enum GML_VERSION  {  GML_3_1, GML_3_2, GML_VERSION_UNKNOWN  };

//  Topologische Klassifikation der Lage eines Punktes bezüglich eines Polygons
enum POINT_LOCATION { IN_POLYGON, OUTSIDE_POLYGON, ON_BOUNDARY, ON_VERTEX, UNKNOWN };

//  Topologische Klassifikation der Lage zweier Polygone
enum AREA_LOCATION  {  DISJUNKT, UEBERLAPPEND, DISJUNKT_BERUEHREND_SINGLE_POINT, DISJUNKT_BERUEHREND_MULTI_POINT, 
                       INNEN_BERUEHREND_SINGLE_POINT, INNEN_BERUEHREND_MULTI_POINT,
					             AUSSEN_BERUEHREND_SINGLE_POINT, AUSSEN_BERUEHREND_MULTI_POINT, INNEN, AUSSEN, GLEICH, UNBESTIMMT  };

// Topologische Klassifikation der Verschneidung zweier Polygone
enum POLYGON_TOPOLOGY {  POLYGONE_DISJUNKT=0, PUNKT_AUF_PUNKT=1, PUNKT_AUF_FLAECHE=2, PUNKT_AUF_LINIE=3, LINIE_AUF_LINIE=4, 
                        LINIE_AUF_FLAECHE=5, FLAECHE_DURCH_FLAECHE=6, FLAECHE_AUF_FLAECHE=7  };

//  Klassifikation der rechtlichen Bedeutung von XPlanGML-Planinhalten
enum RECHTLICHE_BEDEUTUNG {  PLANINHALT, NACHR_UEBERNAHME, SONST_RECHTL_BEDEUTUNG  };

// Klassifikation von Fehlern
enum FEHLER_KLASSIFIKATION { INFORMATION, WARNUNG, FEHLER, SCHWERER_FEHLER };

//  Detaillierte Klassifikation von Geometrietypen
enum GEOMETRY_TYPE  { GEO_POINT, MULTI_GEOMETRY, MULTI_POINT, SURFACE, POLYGON, MULTI_SURFACE, COMPOSITE_SURFACE, SHELL, ORIENTABLE_SURFACE,
                      SOLID, MULTI_SOLID, CURVE, ORIENTABLE_CURVE, MULTI_CURVE, LINE_STRING, LINE_STRING_SEGMENT, ARC_STRING, ARC, CIRCLE, LINEAR_RING, DIRECT_POSITION, 
                      RING, ALLG_GEOMETRIE, IMPLICIT_GEOMETRY, IMPLICIT_GEOMETRY_REFERENCE, GEOMETRY_REFERENCE, SURFACE_REFERENCE, CURVE_REFERENCE,
                      POINT_REFERENCE, SOLID_REFERENCE, COMPOSITE_SOLID, TRIANGULATED_SURFACE, TRIANGLE, GEOMETRIC_COMPLEX, OTHER, NO_GEOMETRY };

//  Aggregierte Klassifikation von Geometrietypen
enum ABSTRACT_GEOMETRY_TYPE  {  ABSTRACT_NO_GEOMETRY, ABSTRACT_POINT, ABSTRACT_RING, ABSTRACT_CURVE, ABSTRACT_SURFACE, ABSTRACT_SOLID, 
                                ABSTRACT_MULTI_GEOMETRY, ABSTRACT_IMPLICIT_GEOMETRY, ABSTRACT_GEOMETRIC_COMPLEX, ABSTRACT_UNKNOWN  };

//  Klassifikation verschiedener Typen von GML-Dictionaries
enum DICTIONARY_TYP {  DICTIONARY_COLLECTION, SINGLE_DICTIONARY, CITYGML_SINGLE_DICTIONARY, CITYGML_DICTIONARY_COLLECTION,
                       BOREHOLEML_DICTIONARY, NO_DICTIONRY  };

//  Klassifikation der Richtung einer Flächen-Normale
enum SURFACE_NORMAL_TYPE { VERTICAL_UPWARD, UPWARD, HORIZONTAL, DOWNWARD, VERTICAL_DOWNWARD, INDIFFERENT  };

//  Klassifikation der CityGML LoD-Stufen
enum CITYGML_LOD { LOD_0, LOD_1, LOD_2, LOD_3, LOD_4, ALL  };

//  Generelle Klaasifikation von GML-Dictionaries
enum DICTIONARY_ENTRY_TYPE {  STANDARD_CODELIST, HIERARCHICAL_CODELIST  };

//  Klassifikation verschiedener Geometrie-Tests
enum GEOMETRY_CHECK  { BASIC_CHECK, ADVANCED_CHECK, PLANARITY_CHECK, SOLID_CHECK, TOPOLOGY_CHECK_XPLANGML_STRICT, TOPOLOGY_CHECK_XPLANGML_LIBERAL, COVERING_CHECK_XPLANGML  };

//  Klassifikation des Ergebnisses eines Geometrietests
enum GEOMETRY_CHECK_RESULT  {  NO_CHECK_PERFORMED, BASIC_CHECK_FAILED, BASIC_CHECK_FULFILLED, ADVANCED_CHECK_FAILED, PLANARITY_CHECK_FAILED, PLANARITY_CHECK_FULFILLED, ADVANCED_CHECK_FULFILLED, TOPOLOGY_CHECK_FAILED, TOPOLOGY_CHECK_FULFILLED  };

// Klassifikation des Umlaufsinnes einer Ringes
enum UMLAUFSINN  {  POSITIVE, NEGATIVE, UNDEFINED };

// Klassifikation des Ergebnisses der Verschneidung zweier Liniensegmente
enum CUT_RESULT  {  NO_CUT, POINT_ON_POINT, POINT_ON_EDGE, TRUE_CUT, OVERLAP };

//  Klassifikation möglicher Darstellungsarten bei der 2D und 3D Visualisierung
enum DARSTELLUNGS_TYP  {  KEINE = 0, STATISCHE_KARTE = 1, INTERAKTIVE_KARTE = 2,
                          INTERAKTIVE_KARTE_FEHLER = 3, KML = 4, GML = 8, DARSTELLUNG_UNKNOWN = 10  };

//  Klassifikation Bauelementen eines Gebäudes
enum BUILDING_ELEMENT_TYPE {  OUTER_WALL, ROOF, GROUND_PLATE, OUTER_DOOR, WINDOW, INTERIOR_WALL, INTERIOR_DOOR, CEILING };

//  Klassifikation der Features im Datenmodell INSPIRE PLU
enum INSPIRE_OBJEKT_TYP  {  SPATIAL_PLAN, ZONING_ELEMENT, SUPPLEMENTARY_RESTRICTION, OFFICIAL_DOCUMENTATION, UNKNOWN_INSPIRE_CLASS  };

